#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

MCU = atmega8

all: build_debug after_build

clean: clean_debug

before_build: 
	./autoVersion/autoVersion_ub

build_debug:
	avr-gcc -mmcu=atmega8 -Wall -DF_CPU=8000000UL -g -std=c99 -I/usr/include -c ADC.c -o obj/Debug/ADC.o
	avr-gcc -mmcu=atmega8 -Wall -DF_CPU=8000000UL -g -std=c99 -I/usr/include -c fuse.c -o obj/Debug/fuse.o
	avr-gcc -mmcu=atmega8 -Wall -DF_CPU=8000000UL -g -std=c99 -I/usr/include -c main.c -o obj/Debug/main.o
	avr-gcc -mmcu=atmega8 -Wall -DF_CPU=8000000UL -g -std=c99 -I/usr/include -c timer.c -o obj/Debug/timer.o
	avr-gcc -mmcu=atmega8 -Wall -DF_CPU=8000000UL -g -std=c99 -I/usr/include -c usart.c -o obj/Debug/usart.o
	avr-g++ -L/usr/lib -o bin/Debug/BUP.elf obj/Debug/ADC.o obj/Debug/fuse.o obj/Debug/main.o obj/Debug/timer.o obj/Debug/usart.o  -mmcu=atmega8 -Wl,-Map=bin/Debug/BUP.map,--cref  
 
after_build: 
	avr-objdump -h -S $(TARGET_OUTPUT_FILE) > $(TARGET_OUTPUT_DIR)$(TARGET_OUTPUT_BASENAME).lss
	avr-objcopy -R .eeprom -R .fuse -R .lock -R .signature -O ihex $(TARGET_OUTPUT_FILE) $(TARGET_OUTPUT_DIR)$(TARGET_OUTPUT_BASENAME).hex
	avr-objcopy --no-change-warnings -j .eeprom --change-section-lma .eeprom=0 -O ihex $(TARGET_OUTPUT_FILE) $(TARGET_OUTPUT_DIR)$(TARGET_OUTPUT_BASENAME).eep
	avr-objcopy --no-change-warnings -j .lock --change-section-lma .lock=0 -O ihex $(TARGET_OUTPUT_FILE) $(TARGET_OUTPUT_DIR)$(TARGET_OUTPUT_BASENAME).lock
	avr-objcopy --no-change-warnings -j .signature --change-section-lma .signature=0 -O ihex $(TARGET_OUTPUT_FILE) $(TARGET_OUTPUT_DIR)$(TARGET_OUTPUT_BASENAME).sig
	avr-objcopy --no-change-warnings -j .fuse --change-section-lma .fuse=0 -O ihex $(TARGET_OUTPUT_FILE) $(TARGET_OUTPUT_DIR)$(TARGET_OUTPUT_BASENAME).fuse
	srec_cat $(TARGET_OUTPUT_DIR)$(TARGET_OUTPUT_BASENAME).fuse -Intel -crop 0x00 0x01 -offset  0x00 -O $(TARGET_OUTPUT_DIR)$(TARGET_OUTPUT_BASENAME).lfs -Intel
	srec_cat $(TARGET_OUTPUT_DIR)$(TARGET_OUTPUT_BASENAME).fuse -Intel -crop 0x01 0x02 -offset -0x01 -O $(TARGET_OUTPUT_DIR)$(TARGET_OUTPUT_BASENAME).hfs -Intel

.PHONY: before_build after_build

